CTCP.WEB/Models/Demo9/Demo9Column.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace CTCP.WEB.Models.Demo9 {

	public class Demo9Column {
		public List<string> command { get; set; }
		public string field { get; set; }
		public string title { get; set; }
		public int width { get; set; } = 150;
		public bool hidden { get; set; } = false;
		public bool locked { get; set; } = false;
		public bool lockable { get; set; } = true;
		public string format { get; set; }
		public string parseFormats { get; set; }
		public string headerTemplate { get; set; }
		public Demo9ColumnFilter filterable { get; set; }
		public HeaderAttributes headerAttributes { get; set; }

	}

	public class HeaderAttributes {
		public string style { get; set; }
	}
}

CTCP.WEB/Models/Demo9/Demo9ColumnFilter.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace CTCP.WEB.Models.Demo9 {

	public class Demo9ColumnFilter {
		public bool extra { get; set; }
	}
}

CTCP.WEB/Models/Demo9/Demo9GridField.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace CTCP.WEB.Models.Demo9 {

	public class Demo9GridField {

		public bool editable { get; set; } = false;
		public string type { get; set; } = "string";
	}
}

CTCP.WEB/Models/Demo9/Demo9GridFields.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace CTCP.WEB.Models.Demo9 {

	public class Demo9GridFields {

		public Demo9GridField c1 { get; set; } = new Demo9GridField();
		public Demo9GridField c2 { get; set; } = new Demo9GridField();
		public Demo9GridField c3 { get; set; } = new Demo9GridField();
		public Demo9GridField c4 { get; set; } = new Demo9GridField { type = "number" };
		public Demo9GridField c5 { get; set; } = new Demo9GridField { type = "number" };
		public Demo9GridField c6 { get; set; } = new Demo9GridField { type = "date" };
		public Demo9GridField c7 { get; set; } = new Demo9GridField { type = "date" };
		public Demo9GridField c8 { get; set; } = new Demo9GridField { type = "date" };
		public Demo9GridField c9 { get; set; } = new Demo9GridField();
		public Demo9GridField c10 { get; set; } = new Demo9GridField { type = "date" };
		public Demo9GridField c11 { get; set; } = new Demo9GridField();
		public Demo9GridField c12 { get; set; } = new Demo9GridField();
		public Demo9GridField c13 { get; set; } = new Demo9GridField { type = "number" };
	}
}

CTCP.WEB/Models/Demo9/Demo9GridModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace CTCP.WEB.Models.Demo9 {

	public class Demo9GridModel {
		public string id { get; set; } = "c1";
		public Demo9GridFields fields { get; set; } = new Demo9GridFields();
	}
}

CTCP.WEB/Models/Demo9/Demo9Item.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace CTCP.WEB.Models.Demo9 {

	public class Demo9Item {
		public string Id { get; set; }
		public string ParentId { get; set; }
		public string Title { get; set; }
		public int Level { get; set; }
	}
}

CTCP.WEB/Controllers/DefaultController.cs
using CTCP.DataAccess.Entities;
using CTCP.DataAccess.Models.Demo;
using CTCP.DataAccess.Repositories;
using CTCP.WEB.Helpers;
using CTCP.WEB.Models;
using CTCP.WEB.Models.Demo9;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System;
using System.Collections.Generic;
using System.Dynamic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace CTCP.WEB.Controllers {

	public class DefaultController : Controller {
		private ICsAgreStore csAgreStore;

		public DefaultController() {

		}

		public DefaultController(ICsAgreStore csAgreStore) {
			this.csAgreStore = csAgreStore;
		}		

		public ActionResult Index() {
			// var sec = Session["User"] as Security;
			// Session[SessionKeys.SITE_MAP_DATA] = SiteMapHelper.GetMenus(sec);

			return View();
		}

		public ActionResult Demo1() {
			return View();
		}

		public ActionResult Demo2() {
			return View();
		}

		public ActionResult Demo3() {
			return View();
		}

		public ActionResult Demo4() {
			return View();
		}

		/// <summary>
		/// Grid simple sample
		/// </summary>
		/// <returns></returns>
		public ActionResult Demo5() {
			return View();
		}

		[HttpPost]
		public ActionResult Demo5_Read(Demo5SearchModel sm) {
			var tuple = csAgreStore.List(sm);

			return Json(new { data = tuple.Item1, pageSize = tuple.Item2 });
		}

		public ActionResult Demo6() {
			return View();
		}

		public ActionResult Demo7() {
			return View();
		}

		public ActionResult Demo8() {
			return View();
		}

		#region 工作清單

		public ActionResult Demo9() {
			return View();
		}

		[HttpPost]
		public ActionResult Demo9_Read(Demo5SearchModel sm) {
			var data = new List<object> {
				new { c1 = "A123456789", c2 = "王測試", c3 = "信用卡、小額貸款", c4 = 12000, c5=56655, c6 = DateTime.Now.ToString("yyyy/MM/dd HH:mm:ss"), c7  = DateTime.Now.ToString("yyyy/MM/dd HH:mm:ss"), c8  = DateTime.Now.ToString("yyyy/MM/dd HH:mm:ss"), c9  = "良好", c10 = DateTime.Now.ToString("yyyy/MM/dd HH:mm:ss"), c11 = "R3", c12 = "禎慧崔", c13 = 88123},
				new { c1 = "A123456789", c2 = "王測試", c3 = "信用卡、小額貸款", c4 = 12000, c5=56655, c6 = DateTime.Now.ToString("yyyy/MM/dd HH:mm:ss"), c7  = DateTime.Now.ToString("yyyy/MM/dd HH:mm:ss"), c8  = DateTime.Now.ToString("yyyy/MM/dd HH:mm:ss"), c9  = "良好", c10 = DateTime.Now.ToString("yyyy/MM/dd HH:mm:ss"), c11 = "R3", c12 = "禎慧崔", c13 = 88123},
				new { c1 = "A123456789", c2 = "王測試", c3 = "信用卡、小額貸款", c4 = 12000, c5=56655, c6 = DateTime.Now.ToString("yyyy/MM/dd HH:mm:ss"), c7  = DateTime.Now.ToString("yyyy/MM/dd HH:mm:ss"), c8  = DateTime.Now.ToString("yyyy/MM/dd HH:mm:ss"), c9  = "良好", c10 = DateTime.Now.ToString("yyyy/MM/dd HH:mm:ss"), c11 = "R3", c12 = "禎慧崔", c13 = 88123},
				new { c1 = "A123456789", c2 = "王測試", c3 = "信用卡、小額貸款", c4 = 12000, c5=56655, c6 = DateTime.Now.ToString("yyyy/MM/dd HH:mm:ss"), c7  = DateTime.Now.ToString("yyyy/MM/dd HH:mm:ss"), c8  = DateTime.Now.ToString("yyyy/MM/dd HH:mm:ss"), c9  = "良好", c10 = DateTime.Now.ToString("yyyy/MM/dd HH:mm:ss"), c11 = "R3", c12 = "禎慧崔", c13 = 88123},
				new { c1 = "A123456789", c2 = "王測試", c3 = "信用卡、小額貸款", c4 = 12000, c5=56655, c6 = DateTime.Now.ToString("yyyy/MM/dd HH:mm:ss"), c7  = DateTime.Now.ToString("yyyy/MM/dd HH:mm:ss"), c8  = DateTime.Now.ToString("yyyy/MM/dd HH:mm:ss"), c9  = "良好", c10 = DateTime.Now.ToString("yyyy/MM/dd HH:mm:ss"), c11 = "R3", c12 = "禎慧崔", c13 = 88123},
				new { c1 = "A123456789", c2 = "王測試", c3 = "信用卡、小額貸款", c4 = 12000, c5=56655, c6 = DateTime.Now.ToString("yyyy/MM/dd HH:mm:ss"), c7  = DateTime.Now.ToString("yyyy/MM/dd HH:mm:ss"), c8  = DateTime.Now.ToString("yyyy/MM/dd HH:mm:ss"), c9  = "良好", c10 = DateTime.Now.ToString("yyyy/MM/dd HH:mm:ss"), c11 = "R3", c12 = "禎慧崔", c13 = 88123},
				new { c1 = "A123456789", c2 = "王測試", c3 = "信用卡、小額貸款", c4 = 12000, c5=56655, c6 = DateTime.Now.ToString("yyyy/MM/dd HH:mm:ss"), c7  = DateTime.Now.ToString("yyyy/MM/dd HH:mm:ss"), c8  = DateTime.Now.ToString("yyyy/MM/dd HH:mm:ss"), c9  = "良好", c10 = DateTime.Now.ToString("yyyy/MM/dd HH:mm:ss"), c11 = "R3", c12 = "禎慧崔", c13 = 88123},
				new { c1 = "A123456789", c2 = "王測試", c3 = "信用卡、小額貸款", c4 = 12000, c5=56655, c6 = DateTime.Now.ToString("yyyy/MM/dd HH:mm:ss"), c7  = DateTime.Now.ToString("yyyy/MM/dd HH:mm:ss"), c8  = DateTime.Now.ToString("yyyy/MM/dd HH:mm:ss"), c9  = "良好", c10 = DateTime.Now.ToString("yyyy/MM/dd HH:mm:ss"), c11 = "R3", c12 = "禎慧崔", c13 = 88123},
				new { c1 = "A123456789", c2 = "王測試", c3 = "信用卡、小額貸款", c4 = 12000, c5=56655, c6 = DateTime.Now.ToString("yyyy/MM/dd HH:mm:ss"), c7  = DateTime.Now.ToString("yyyy/MM/dd HH:mm:ss"), c8  = DateTime.Now.ToString("yyyy/MM/dd HH:mm:ss"), c9  = "良好", c10 = DateTime.Now.ToString("yyyy/MM/dd HH:mm:ss"), c11 = "R3", c12 = "禎慧崔", c13 = 88123},
				new { c1 = "A123456789", c2 = "王測試", c3 = "信用卡、小額貸款", c4 = 12000, c5=56655, c6 = DateTime.Now.ToString("yyyy/MM/dd HH:mm:ss"), c7  = DateTime.Now.ToString("yyyy/MM/dd HH:mm:ss"), c8  = DateTime.Now.ToString("yyyy/MM/dd HH:mm:ss"), c9  = "良好", c10 = DateTime.Now.ToString("yyyy/MM/dd HH:mm:ss"), c11 = "R3", c12 = "禎慧崔", c13 = 88123},
				new { c1 = "A123456789", c2 = "王測試", c3 = "信用卡、小額貸款", c4 = 12000, c5=56655, c6 = DateTime.Now.ToString("yyyy/MM/dd HH:mm:ss"), c7  = DateTime.Now.ToString("yyyy/MM/dd HH:mm:ss"), c8  = DateTime.Now.ToString("yyyy/MM/dd HH:mm:ss"), c9  = "良好", c10 = DateTime.Now.ToString("yyyy/MM/dd HH:mm:ss"), c11 = "R3", c12 = "禎慧崔", c13 = 88123},
				new { c1 = "A123456789", c2 = "王測試", c3 = "信用卡、小額貸款", c4 = 15000, c5=56655, c6 = DateTime.Now.ToString("yyyy/MM/dd HH:mm:ss"), c7  = DateTime.Now.ToString("yyyy/MM/dd HH:mm:ss"), c8  = DateTime.Now.ToString("yyyy/MM/dd HH:mm:ss"), c9  = "良好", c10 = DateTime.Now.ToString("yyyy/MM/dd HH:mm:ss"), c11 = "R3", c12 = "禎慧崔", c13 = 88123},
				new { c1 = "A123456789", c2 = "王測試", c3 = "信用卡、小額貸款", c4 = 15000, c5=56655, c6 = DateTime.Now.ToString("yyyy/MM/dd HH:mm:ss"), c7  = DateTime.Now.ToString("yyyy/MM/dd HH:mm:ss"), c8  = DateTime.Now.ToString("yyyy/MM/dd HH:mm:ss"), c9  = "良好", c10 = DateTime.Now.ToString("yyyy/MM/dd HH:mm:ss"), c11 = "R3", c12 = "禎慧崔", c13 = 88123},
				new { c1 = "A123456789", c2 = "王測試", c3 = "信用卡、小額貸款", c4 = 16000, c5=56655, c6 = DateTime.Now.ToString("yyyy/MM/dd HH:mm:ss"), c7  = DateTime.Now.ToString("yyyy/MM/dd HH:mm:ss"), c8  = DateTime.Now.ToString("yyyy/MM/dd HH:mm:ss"), c9  = "良好", c10 = DateTime.Now.ToString("yyyy/MM/dd HH:mm:ss"), c11 = "R3", c12 = "禎慧崔", c13 = 88123},
			};

			return Json(new {
				data,
				pageSize = data.Count });
		}

		/// <summary>
		/// 讀取所有欄位
		/// </summary>
		/// <returns></returns>
		[HttpPost]
		public ActionResult Demo9_LoadGridInfo() {
			return Json(new {
				columns = MakeGridColumns(),
				model = MakeGridModel()
			});
		}

		private List<Demo9Column> MakeGridColumns() {
			var list = new List<Demo9Column>() {
				new Demo9Column { field = "c1", title = "統一編號", locked = true, lockable = true },
				new Demo9Column { field = "c2", title = "客戶姓名", },
				new Demo9Column { field = "c3", title = "產品別", },
				new Demo9Column { field = "c4", title = "應收合計", },
				new Demo9Column { field = "c5", title = "呆帳餘額", },
				new Demo9Column { field = "c6", title = "最近聯絡日", format = "{0:yyyy/MM/dd}", parseFormats ="yyyy/MM/dd hh:mm:ss", filterable = new Demo9ColumnFilter { extra = true} },
				new Demo9Column { field = "c7", title = "Callback", format = "{0:yyyy/MM/dd}", parseFormats ="yyyy/MM/dd hh:mm:ss", filterable = new Demo9ColumnFilter { extra = true}  },
				new Demo9Column { field = "c8", title = "最近繳款日", format = "{0:yyyy/MM/dd}", parseFormats ="yyyy/MM/dd hh:mm:ss", filterable = new Demo9ColumnFilter { extra = true}  },
				new Demo9Column { field = "c9", title = "還款態樣", },
				new Demo9Column { field = "c10", title = "分案日", format = "{0:yyyy/MM/dd}", parseFormats ="yyyy/MM/dd hh:mm:ss", filterable = new Demo9ColumnFilter { extra = true} },
				new Demo9Column { field = "c11", title = "SubSegment", },
				new Demo9Column { field = "c12", title = "催收員", },
				new Demo9Column { field = "c13", title = "分機", },
			};

			var extraColumns = GetExtraColumns();
			list.AddRange(GetExtraColumns());

			if (extraColumns.Count > 0) {
				list.Add(new Demo9Column { command = new List<string> { "edit" }, title = "動作", width = 100 });
			}

			var hiddenColumns = GetHiddenColumns();
			list.ForEach(c => {
				c.hidden = hiddenColumns.Any(h => h == c.field);
			});

			return list;
		}

		private Demo9GridModel MakeGridModel() {
			var model =  new Demo9GridModel();
			return model;
		}

		/// <summary>
		/// 儲存自定義欄位
		/// </summary>
		[HttpPost]
		public ActionResult Demo9_SaveExtraColumn(string title) {
			var extraColumns = GetExtraColumns();
			extraColumns.Add(new Demo9Column() { title = title, field = $"guid_{Guid.NewGuid().ToString("N")}" });

			Session["Demo9_ExtraColumns"] = extraColumns;
			return Json(new { result = "success" });
		}

		/// <summary>
		/// 讀取自定義欄位
		/// </summary>
		/// <returns></returns>
		[HttpPost]
		public ActionResult Demo9_ListExtraColumns() {
			var extraColumns = GetExtraColumns();
			return Json(extraColumns);
		}

		/// <summary>
		/// 刪除自定義欄位
		/// </summary>
		/// <param name="field"></param>
		/// <returns></returns>
		[HttpPost]
		public ActionResult Demo9_RemoveExtraColumn(string field) {
			var extraColumns = GetExtraColumns();
			var column = extraColumns.Where(c => c.field == field).FirstOrDefault();
			extraColumns.Remove(column);
			Session["Demo9_ExtraColumns"] = extraColumns;
			return Json(new { });
		}

		/// <summary>
		/// 儲存要顯示/隱藏的欄位
		/// </summary>
		[HttpPost]
		public ActionResult Demo9_SaveHiddenColumn(string field, bool isHidden) {
			var list = GetHiddenColumns();

			var hasData = list.Any(c => c == field);
			if (isHidden && !hasData) {
				list.Add(field);

			} else if(!isHidden && hasData) {
				list.Remove(list.Where(c => c == field).FirstOrDefault());
			}

			Session["Demo9_HiddenColumns"] = list;
			return Json(new { result = "success" });
		}

		/// <summary>
		/// 科、組、員下拉式選單

CTCP.WEB/Views/Default/Demo1.cshtml
@{
	ViewBag.Title = "Demo1";
}

@section css {
	<style>
	</style>
}

<div id="example">
	<div class="demo-section k-content wide">
		<div id="chart"></div>
		<br />
		<div id="chart2"></div>
	</div>
</div>

@section scripts {
	<script>

		function createChart(id) {
			$(id).kendoChart({
				title: {
					text: "Average Weather Conditions"
				},
				series: [{
					type: "rangeArea",
					data: [[5, 11], [5, 13], [7, 15], [10, 19], [13, 23], [17, 28],
					[20, 30], [20, 30], [17, 26], [13, 22], [9, 16], [6, 13]]
				}],
				seriesDefaults: {
					labels: {
						visible: true,
						from: {
							template: "#=value.from# °C",
						},
						to: {
							template: "#=value.to# °C",
						}
					}
				},
				categoryAxis: {
					categories: ["January", "February", "March", "April", "May", "June", "July", "August", "September", "October", "November", "December"],
					labels: {
						rotation: "auto"
					}
				},
				tooltip: {
					visible: true,
					template: "Avg Min Temp : #= value.from # °C <br>" +
						"Avg Max Temp : #= value.to # °C"
				}
			});
		}

		$(document).ready(createChart('#chart'));
		$(document).ready(createChart('#chart2'));
		$(document).bind("kendo:skinChange", createChart);

	</script>
}

CTCP.WEB/Views/Default/Demo10.cshtml
@{
//Layout = "/Views/Shared/_SimpleLayout.cshtml";
}

@section css {
	<style>

	</style>
}

<div id="grid"></div>

@section scripts {
<script>

		var dataSource = new kendo.data.DataSource({
			transport: {
				read: {
					url: '@Url.Action("Demo10_Read")',
					type: 'post',
					dataType: 'json',
					data: {
						cond1: 'cond1',
						cond2: 'cond2',
						cond3: 999
					}
				},
				update: {
					url: '@Url.Action("Demo10_Update")',
					type: 'post',
					dataType: 'json',
				},
				parameterMap: function (options, operation) {
					if (operation !== 'read' && options.models) {
						var json = JSON.stringify(options.models[0]);
						console.log(json);
						return json;
					}
					return options;
				}
			},
			batch: false,
			schema: {
				data: 'data',
				total: 'pageSize',
				model: {
					id: 'cAgreNum',
					fields: {
						cAgreNum: { editable: false },
						cPtyId: { editable: true, nullable: true },
					}
				}
			},
			pageSize: 20,
			serverPaging: true,
			serverFiltering: true,
			serverSorting: true,
			error: function (e) {
				alert("Errors: " + e.errors);
			},
			requestEnd: function (e) {
				if (e.type === 'read' && !e.response.Errors) {
					// alert('查詢成功');

				} else if (e.type === 'update' && !e.response.Errors) {
					alert(e.response.Message);
				}
			}
		});

		$(document).ready(function () {
			$('#grid').kendoGrid({
				dataSource: dataSource,
				filterable: true,
				sortable: true,
				pageable: true,
				toolbar: ['search'],
				editable: 'inline',
				columnMenu: true,
				reorderable: true,
				pageable: {
					refresh: true,
				},
				columns: [
				{
					command: ['edit'],
					title: 'Action',
					width: '100px',
				},
				{
					field: 'cAgreNum',
					title: 'cAgreNum',
					width: 200,
					locked: true,
					lockable: true,
				},
				{
					field: 'cPtyId',
					title: 'cPtyId',
					width: 150
				}, {
					field: 'cClitCode',
					title: 'cClitCode',
					width: 150
				}, {
					field: 'cAcctBnch',
					title: 'cAcctBnch',
					width: 150
				}, {
					field: 'cAcct',
					title: 'cAcct',
					width: 150
				}, {
					field: 'cSordAcct',
					title: 'cSordAcct',
					width: 150
				}, {
					field: 'cIdNo',
					title: 'cIdNo',
					width: 150
				}, {
					field: 'cThirdPtyType',
					title: 'cThirdPtyType',
					width: 150
				}, {
					field: 'cSecType',
					title: 'cSecType',
					width: 150
				}, {
					field: 'cSecCode',
					title: 'cSecCode',
					width: 150
				}, {
					field: 'cArreStsCode',
					title: 'cArreStsCode',
					width: 150
				}, {
					field: 'cColtType',
					title: 'cColtType',
					width: 150
				}, {
					field: 'cACStsType',
					title: 'cACStsType',
					width: 150
				}
				]
			});
		});

</script>
}

CTCP.WEB/Views/Default/Demo11.cshtml
@{
//Layout = "/Views/Shared/_SimpleLayout.cshtml";
}

@section css {
	<style>

	</style>
}

<div id="grid"></div>

@section scripts {
	<script>

		var dataSource = new kendo.data.DataSource({
			transport: {
				read: {
					url: '@Url.Action("Demo10_Read")',
					type: 'post',
					dataType: 'json',
					data: {
						cond1: 'cond1',
						cond2: 'cond2',
						cond3: 999
					}
				}
			},
			schema: {
				data: 'data',
				total: "pageSize"
			},
			pageSize: 20,
			serverPaging: true,
			serverFiltering: true,
			serverSorting: true
		}); 

		$(document).ready(function () {
			$('#grid').kendoGrid({
				dataSource: dataSource,
				height: 600,
				filterable: false,
				sortable: true,
				pageable: true,
				scrollable: {
					endless: true,
					//virtual: 'columns'
				},
				toolbar: ['search'],
				search: {
					fields: ['cAcct'] // Or, specify multiple fields by adding them to the array, e.g ["name", "age"]
				},
				columnMenu: true,
				pageable: {
					numeric: false,
					previousNext: false
				},
				columns: [{
					field: 'cAgreNum',
					title: 'cAgreNum',
					width: 200,
				},
				{
					field: 'cPtyId',
					title: 'cPtyId',
					width: 150
				}, {
					field: 'cClitCode',
					title: 'cClitCode',
					width: 150
				}, {
					field: 'cAcctBnch',
					title: 'cAcctBnch',
					width: 150
				}, {
					field: 'cAcct',
					title: 'cAcct',
					width: 150
				}, {
					field: 'cSordAcct',
					title: 'cSordAcct',
					width: 150
				}, {
					field: 'cIdNo',
					title: 'cIdNo',
					width: 150
				}, {
					field: 'cPtyId',
					title: 'cPtyId',
					width: 150
				}, {
					field: 'cThirdPtyType',
					title: 'cThirdPtyType',
					width: 150
				}, {
					field: 'cSecType',
					title: 'cSecType',
					width: 150
				}, {
					field: 'cSecCode',
					title: 'cSecCode',
					width: 150
				}, {
					field: 'cArreStsCode',
					title: 'cArreStsCode',
					width: 150
				}, {
					field: 'cColtType',
					title: 'cColtType',
					width: 150
				}, {
					field: 'cACStsType',
					title: 'cACStsType',
					width: 150
				}
				]
			});
		});

	</script>
}

CTCP.WEB/Views/Default/Demo12.cshtml
@{
//Layout = "/Views/Shared/_SimpleLayout.cshtml";
}

@section css {
	<style>

	</style>
}

<div id="grid"></div>

<ul id="context-menu">
	<li id="addRow">新增</li>
	<li id="editRow">編輯</li>
	<li id="removeRow">刪除</li>
	<li id="viewRow">明細</li>
</ul>

@section scripts {
<script>

		var dataSource = new kendo.data.DataSource({
			transport: {
				read: {
					url: '@Url.Action("Demo12_Read")',
					type: 'post',
					dataType: 'json',
					data: {
						cond1: 'cond1',
						cond2: 'cond2',
						cond3: 999
					}
				},
			},
			batch: false,
			schema: {
				data: 'data',
				total: 'pageSize',
				model: {
					id: 'cAgreNum',
					fields: {
						cAgreNum: { editable: false },
						cPtyId: { editable: true, nullable: true },
					}
				}
			},
			pageSize: 20,
			serverPaging: true,
			serverFiltering: true,
			serverSorting: true,
			error: function (e) {
				alert("Errors: " + e.errors);
			},
			requestEnd: function (e) {
				if (e.type === 'read' && !e.response.Errors) {
					// alert('查詢成功');

				} else if (e.type === 'update' && !e.response.Errors) {
					alert(e.response.Message);
				}
			}
		});

		$(document).ready(function () {
			$('#grid').kendoGrid({
				dataSource: dataSource,
				filterable: true,
				sortable: true,
				pageable: true,
				toolbar: ['search'],
				editable: 'inline',
				columnMenu: true,
				reorderable: true,
				pageable: {
					refresh: true,
				},
				columns: [
				{
					command: ['edit'],
					title: 'Action',
					width: '100px',
				},
				{
					field: 'cAgreNum',
					title: 'cAgreNum',
					width: 200,
					locked: true,
					lockable: true,
				},
				{
					field: 'cPtyId',
					title: 'cPtyId',
					width: 150
				}, {
					field: 'cClitCode',
					title: 'cClitCode',
					width: 150
				}, {
					field: 'cAcctBnch',
					title: 'cAcctBnch',
					width: 150
				}, {
					field: 'cAcct',
					title: 'cAcct',
					width: 150
				}, {
					field: 'cSordAcct',
					title: 'cSordAcct',
					width: 150
				}, {
					field: 'cIdNo',
					title: 'cIdNo',
					width: 150
				}, {
					field: 'cThirdPtyType',
					title: 'cThirdPtyType',
					width: 150
				}, {
					field: 'cSecType',
					title: 'cSecType',
					width: 150
				}, {
					field: 'cSecCode',
					title: 'cSecCode',
					width: 150
				}, {
					field: 'cArreStsCode',
					title: 'cArreStsCode',
					width: 150
				}, {
					field: 'cColtType',
					title: 'cColtType',
					width: 150
				}, {
					field: 'cACStsType',
					title: 'cACStsType',
					width: 150
				}
				]
			});

			$('#context-menu').kendoContextMenu({
				target: '#grid',
				filter: 'td',
				select: function (e) {
					var row = $(e.target).parent()[0];
					var grid = $('#grid').data('kendoGrid');
					var item = e.item.id;

					var selectedItem = grid.dataItem(row);

					switch (item) {
						case 'addRow':
							grid.addRow();
							break;
						case 'editRow':
							grid.editRow(row);
							break;
						case 'removeRow':
							grid.removeRow(row);
							break;
						default:
							alert('I want to see ' + selectedItem.cAgreNum);
							break;
					};
				}
			});
		});


</script>
}

CTCP.WEB/Views/Default/Hello.cshtml
@{
	ViewBag.Title = "Hello";
	// Layout = null; 
}

<h2>Hello 123</h2>

CTCP.WEB/Views/Default/Index.cshtml
@{
	ViewBag.Title = "Index";
}

@section css {
	<style>

		.iframe_content {
			width: 100%;
			height: 700px;
			border: 0;
			overflow: hidden;
		}

	</style>
}

@*<iframe class="iframe_content" src="@Url.Action("Hello", "Default")"></iframe>*@
<iframe class="iframe_content" src="~/Front/worklist.aspx"></iframe>